### ISSUE TITLE
Audio stream

### ISSUE THREAD

**Issue by gamecompiler** [rfw/python-mumble#2]
Hi, is audio streaming implemented?
I would like to send/receive audio from the mumble server when triggered over a function.
(To be able to implement a Walkie-Talkie like feature)
Thought i could use it for an simple PMR Gateway like eQSO or FRN.

Thanks in advance.
gamecompiler

**Comment by rfw** [comment]
This library is a little rusty but from the best of my knowledge:

- Both CELT codecs work for receiving, provided you have the libraries (see submodules).
- Opus support is missing cffi bindings.
- Audio transmission may be supported.
- All audio support is via TCP tunnel; there is no UDP support because of missing AES-OCB​.

I don't have the time to implement full support myself, but feel free to submit a pull request.
